interface DoubleMatrix {
		void DoubleMatrix(long rows, long columns);
		void DoubleMatrix(long rows, long columns, double fillValue);
		long getRowsCount();
		long getColumnsCount();
		double getValue(long row, long column);
		double setValue(long row, long column, double val);
		
		[Const] DOMString asString();
		
		[Value] DoubleMatrix scalarMul(double scalar);
		[Value] DoubleMatrix matrixMul([Ref]DoubleMatrix scalar);
		[Value] DoubleMatrix transpose();
		[Value] DoubleMatrix swapColumns(long colA, long colB);
		[Value] DoubleMatrix swapRows(long rowA, long rowB);
		[Value] DoubleMatrix concat([Ref] DoubleMatrix B);
		
		void split(long splitColumn, [Ref] DoubleMatrix left, [Ref] DoubleMatrix right);
		boolean toLU([Ref] DoubleMatrix L, [Ref] DoubleMatrix U);
		
		boolean equal([Ref] DoubleMatrix B);
				
		[Value] static DoubleMatrix getIdentity(long rows, long columns);
};